const assert=require('node:assert/strict');
const e=require('./dist/recommendations.js');
const favorite=e.enrich({video_id:'favorite001',title:'Sunday Suspense | Byomkesh | Saradindu Bandyopadhyay',confirmed_favorite:true});
const related=e.enrich({video_id:'related0001',title:'Byomkesh | Saradindu Bandyopadhyay'});
const generic=e.enrich({video_id:'generic0001',title:'A suspense story'});
const plain=e.enrich({video_id:'plain000001',title:'Sunday Suspense | A literary story'});
const shonku=e.enrich({video_id:'shonku00001',title:'Prof Shonku O Moru Rahasya'});
const unrelated=e.enrich({video_id:'other000001',title:'Romantic Premer Golpo'});
assert(!plain.title_keyword_tags.includes('suspense'),'Show branding must not become a genre');
assert(shonku.title_keyword_tags.includes('science fiction'));
assert(shonku.authors.includes('Satyajit Ray'));
let profile=e.profile([favorite,related,generic],{});
assert.equal(profile.series.get('Byomkesh'),3,'Confirmed favorites are strong signals without a like click');
assert(e.evaluate(related,profile,{}).score>e.evaluate(generic,profile,{}).score);
assert.equal(e.evaluate(related,profile,{}).reason,'Because you like Byomkesh.');
assert.equal(e.rank([related,unrelated],profile,{related0001:{heard:true}})[1].video_id,related.video_id,'Heard stories go below unheard choices');
assert.equal(e.evaluate(related,profile,{related0001:{saved:true}}).score-e.evaluate(related,profile,{}).score,2);
assert.equal(e.profile([favorite],{favorite001:{disliked:true}}).series.size,0,'Hidden favorite stops influencing taste');
assert.equal(e.profile([favorite],{favorite001:{disliked:false}}).series.get('Byomkesh'),3);
console.log('Passed ranking, reasons, tagging, heard penalty, save boost and hidden-favorite restoration checks.');
